"""
pipeline/retrain.py — Auto-Retrain Pipeline with FITS Change Detection
=======================================================================
Detects when new FITS files are added to data/raw/ and automatically
runs the full pipeline: ingest → detect → train → validate → export.

Uses a manifest (hash of file sizes + mtimes) so it only retrains when
the actual data files change, not just when the script is run.

Usage:
    python pipeline/retrain.py              # retrain only if FITS files changed
    python pipeline/retrain.py --force     # always retrain regardless
    python pipeline/retrain.py --check     # check manifest only, don't run
    python pipeline/retrain.py --watch     # watch data/raw/ and auto-retrain on changes
    python pipeline/retrain.py --export-only  # just re-export static files
"""

import argparse
import hashlib
import json
import logging
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

BASE_DIR = Path(__file__).parent.parent
RAW_DIR  = BASE_DIR / "data" / "raw"
PROC_DIR = BASE_DIR / "data" / "processed"
MANIFEST = PROC_DIR / ".manifest.json"


# ─── Manifest ────────────────────────────────────────────────────────────────

def compute_manifest() -> dict:
    """
    Build a manifest of all FITS files in data/raw/.
    Uses file size + mtime (fast) rather than SHA hashing huge FITS files.
    """
    manifest = {"files": {}, "computed_at": datetime.now(timezone.utc).isoformat()}
    fits_files = sorted(RAW_DIR.rglob("*.fits"))

    for f in fits_files:
        stat = f.stat()
        manifest["files"][str(f.relative_to(BASE_DIR))] = {
            "size": stat.st_size,
            "mtime": stat.st_mtime,
        }

    manifest["file_count"] = len(fits_files)
    hel1os_count = len(list((RAW_DIR / "hel1os").rglob("*.fits"))) if (RAW_DIR / "hel1os").exists() else 0
    solexs_count = len(list((RAW_DIR / "solexs").rglob("*.fits"))) if (RAW_DIR / "solexs").exists() else 0
    manifest["hel1os_count"] = hel1os_count
    manifest["solexs_count"] = solexs_count
    return manifest


def load_manifest() -> dict | None:
    if MANIFEST.exists():
        with open(MANIFEST) as f:
            return json.load(f)
    return None


def save_manifest(manifest: dict):
    PROC_DIR.mkdir(parents=True, exist_ok=True)
    with open(MANIFEST, "w") as f:
        json.dump(manifest, f, indent=2)


def data_has_changed() -> tuple[bool, dict, dict | None]:
    """Returns (changed, current_manifest, old_manifest)."""
    current = compute_manifest()
    old = load_manifest()

    if old is None:
        log.info("No manifest found — first run, will process data")
        return True, current, None

    if current["files"] != old.get("files", {}):
        new_count = current["file_count"]
        old_count = old.get("file_count", 0)
        log.info(f"Data changed: {old_count} → {new_count} FITS files")
        return True, current, old

    log.info(f"No data changes detected ({current['file_count']} FITS files, manifest unchanged)")
    return False, current, old


# ─── Pipeline Steps ───────────────────────────────────────────────────────────

def run_step(cmd: list[str], step_name: str) -> bool:
    """Run a pipeline step subprocess. Returns True if successful."""
    log.info(f"\n{'─'*60}")
    log.info(f"▶ {step_name}")
    log.info(f"  Command: {' '.join(cmd)}")
    log.info(f"{'─'*60}")
    t0 = time.time()

    result = subprocess.run(
        cmd,
        cwd=str(BASE_DIR),
        capture_output=False,  # stream output directly to terminal
    )

    elapsed = time.time() - t0
    if result.returncode != 0:
        log.error(f"✗ {step_name} FAILED (exit code {result.returncode}) after {elapsed:.1f}s")
        return False

    log.info(f"✓ {step_name} completed in {elapsed:.1f}s")
    return True


def clear_processed_outputs():
    """Remove derived files that will be regenerated by the pipeline."""
    files_to_clear = [
        PROC_DIR / "lightcurve.csv",
        PROC_DIR / "hel1os_lightcurve.csv",
        PROC_DIR / "solexs_lightcurve.csv",
        PROC_DIR / "flares.json",
        PROC_DIR / "model.joblib",
        PROC_DIR / "model_metrics.json",
        PROC_DIR / "validation_report.json",
        PROC_DIR / "validation_report.txt",
    ]
    cleared = 0
    for f in files_to_clear:
        if f.exists():
            f.unlink()
            cleared += 1
    log.info(f"  Cleared {cleared} processed output files")


def run_full_pipeline(python: str = sys.executable) -> bool:
    """
    Execute the full pipeline: ingest → detect → train → validate → export.
    Returns True if all steps succeeded.
    """
    log.info("\n" + "=" * 60)
    log.info("SOLAR SENTINEL — FULL PIPELINE RUN")
    log.info(f"Started: {datetime.now(timezone.utc).isoformat()}")
    log.info("=" * 60)

    t_start = time.time()

    steps = [
        (
            [python, "pipeline/ingest.py",
             "--input", "data/raw",
             "--output", "data/processed/lightcurve.csv"],
            "Step 1: Data Ingestion (HEL1OS + SoLEXS sensor fusion)"
        ),
        (
            [python, "pipeline/detect_flares.py",
             "--input",  "data/processed/lightcurve.csv",
             "--output", "data/processed/flares.json"],
            "Step 2: Flare Detection (k-sigma threshold algorithm)"
        ),
        (
            [python, "pipeline/train_model.py"],
            "Step 3: ML Model Training (XGBoost flare predictor)"
        ),
        (
            [python, "pipeline/validate.py",
             "--flares", "data/processed/flares.json",
             "--output", "data/processed/validation_report.txt"],
            "Step 4: NOAA Validation (cross-check against ground truth)"
        ),
        (
            [python, "export_static.py"],
            "Step 5: Export Static Files (sync frontend data)"
        ),
    ]

    for cmd, step_name in steps:
        ok = run_step(cmd, step_name)
        if not ok:
            log.error(f"\n✗ Pipeline halted at: {step_name}")
            return False

    elapsed = time.time() - t_start
    log.info("\n" + "=" * 60)
    log.info(f"✓ Full pipeline completed in {elapsed:.0f}s")
    log.info("=" * 60)
    return True


def run_export_only(python: str = sys.executable) -> bool:
    """Just re-export static files without retraining."""
    return run_step(
        [python, "export_static.py"],
        "Export Static Files (sync frontend data)"
    )


# ─── Watch Mode ───────────────────────────────────────────────────────────────

def watch_mode(poll_interval: int = 30):
    """
    Continuously poll data/raw/ for new FITS files.
    On change, run the full pipeline automatically.
    """
    log.info(f"👁 Watch mode — polling data/raw/ every {poll_interval}s for new FITS files")
    log.info("Press Ctrl+C to stop.\n")

    last_manifest = load_manifest()

    try:
        while True:
            time.sleep(poll_interval)
            changed, current, _ = data_has_changed()
            if changed:
                log.info("🔄 New data detected — triggering full retrain...")
                success = run_full_pipeline()
                if success:
                    save_manifest(current)
                    log.info("✓ Retrain complete. Watching for more changes...")
                else:
                    log.error("✗ Retrain failed. Will retry on next change.")
            else:
                log.debug(f"No changes — next check in {poll_interval}s")
    except KeyboardInterrupt:
        log.info("\nWatch mode stopped by user.")


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Solar Sentinel — Auto-retrain pipeline runner"
    )
    parser.add_argument("--force",       action="store_true", help="Always retrain, ignore manifest")
    parser.add_argument("--check",       action="store_true", help="Check manifest only, don't run pipeline")
    parser.add_argument("--watch",       action="store_true", help="Watch data/raw/ and auto-retrain on changes")
    parser.add_argument("--export-only", action="store_true", help="Re-export static files only (no retrain)")
    parser.add_argument("--poll",        type=int, default=30, help="Watch mode poll interval in seconds (default: 30)")
    parser.add_argument("--no-clear",    action="store_true", help="Don't clear processed files before retrain")
    args = parser.parse_args()

    python = sys.executable

    if args.watch:
        watch_mode(poll_interval=args.poll)
        return

    if args.export_only:
        run_export_only(python)
        return

    if args.check:
        changed, current, old = data_has_changed()
        print(f"\nFITS files: {current['file_count']} total "
              f"({current['hel1os_count']} HEL1OS, {current['solexs_count']} SoLEXS)")
        if old:
            print(f"Last manifest: {old.get('computed_at', 'unknown')}")
        print(f"Data changed since last run: {'YES' if changed else 'NO'}")
        if changed:
            print("→ Run without --check to trigger retrain")
        return

    # Normal mode: retrain if changed (or --force)
    changed, current, old = data_has_changed()

    if not changed and not args.force:
        log.info("✓ Data unchanged since last run. Use --force to retrain anyway.")
        # Still re-export in case the code changed
        run_export_only(python)
        return

    if not args.no_clear:
        log.info("Clearing processed outputs before retrain...")
        clear_processed_outputs()

    success = run_full_pipeline(python)

    if success:
        save_manifest(current)
        log.info(f"✓ Manifest updated: {current['file_count']} FITS files tracked")
    else:
        log.error("Pipeline failed — manifest NOT updated. Fix errors and re-run.")
        sys.exit(1)


if __name__ == "__main__":
    main()
